export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGIN_RESET = 'USER_LOGIN_RESET';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_REGISTER_ACTIVATION_REQUEST =
  'USER_REGISTER_ACTIVATION_REQUEST';
export const USER_REGISTER_ACTIVATION_SUCCESS =
  'USER_REGISTER_ACTIVATION_SUCCESS';
export const USER_REGISTER_ACTIVATION_FAIL = 'USER_REGISTER_ACTIVATION_FAIL';

export const USER_GOOGLE_LOGIN_REQUEST = 'USER_GOOGLE_LOGIN_REQUEST';
export const USER_GOOGLE_LOGIN_SUCCESS = 'USER_GOOGLE_LOGIN_SUCCESS';
export const USER_GOOGLE_LOGIN_FAIL = 'USER_GOOGLE_LOGIN_FAIL';

export const USER_FACEBOOK_LOGIN_REQUEST = 'USER_FACEBOOK_LOGIN_REQUEST';
export const USER_FACEBOOK_LOGIN_SUCCESS = 'USER_FACEBOOK_LOGIN_SUCCESS';
export const USER_FACEBOOK_LOGIN_FAIL = 'USER_FACEBOOK_LOGIN_FAIL';

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_RESET = 'CART_RESET';
